name: Deploy site

on:
  push:
    branches:
      - main

# TODO - add devcontainer build/run to build hugo site (can later add lunr index pre-building!)

jobs:
  build_and_deploy:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: ubuntu-latest
    environment: production
    name: Build and Deploy
    steps:
      - name: Checkout source
        uses: actions/checkout@v2

      - name: Set up Docker BuildKit
        uses: docker/setup-buildx-action@v1

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1 
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Fixup mount folders
        run: mkdir -p ~/.config/gh

      - name: Build and run dev container task
        uses: devcontainers/ci@v0.3
        with:
          imageName: ghcr.io/stuartleeks/stuartleeks-com-devcontainer
          runCmd: make ci-build

       # https://docs.microsoft.com/en-gb/azure/static-web-apps/build-configuration?tabs=github-actions#build-configuration
      - name: Deploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          repo_token: ${{ secrets.GITHUB_TOKEN }} # Used for Github integrations (i.e. PR comments)
          action: "upload"
          ###### Repository/Build Configurations - These values can be configured to match your app requirements. ######
          # For more information regarding Static Web App workflow configurations, please visit: https://aka.ms/swaworkflowconfig
          app_location: "public"
          skip_app_build: true # The content is built in the dev container step - using this action to publish
          ###### End of Repository/Build Configurations ######

